#!/usr/bin/env bash

# WARNING: the lack of initial "cd" is intentional.
# This script is strictly meant to be sourced from the scp'd bootstrap script.
# Refer to installer/boot/bootstrap.sh for the working directory.

# shellcheck source=shared.packages.sh
source installer/start/shared.packages.sh
# shellcheck source=../../scripts/aliased/install.node.sh
source scripts/aliased/install.node.sh
# shellcheck source=../../scripts/aliased/hook.alias.sh
source scripts/aliased/hook.alias.sh
# shellcheck source=../../scripts/aliased/install.clone-repos.sh
source scripts/aliased/install.clone-repos.sh
# shellcheck source=../../scripts/aliased/install.apps.sh
source scripts/aliased/install.apps.sh
# shellcheck source=../../scripts/aliased/hook.docs.sh
source scripts/aliased/hook.docs.sh
#
# Maybe clean this up, but the idea is to automatically install
# the cli we use to bootstrap the system on our laptop.
#
SOFTWARE_NAME="devos"
SOURCE_BIN_PATH="/root/.$SOFTWARE_NAME/bin/$SOFTWARE_NAME"
BIN_PATH="/usr/local/bin/$SOFTWARE_NAME"
if [ -f "$BIN_PATH" ]; then
  rm -f "$BIN_PATH"
fi
{
  echo "#!/usr/bin/env bash"
  echo ""
  echo "# This script was generated by the devos installer at $(date)."
  echo ""
  echo "$SOURCE_BIN_PATH \"\$@\""
} >>"$BIN_PATH"
chmod +x "$SOURCE_BIN_PATH"
chmod +x "$BIN_PATH"
