#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

# shellcheck source=../lib/defaults.sh
source ../lib/defaults.sh
# shellcheck source=../lib/runtime.sh
source scripts/lib/runtime.sh

runtime_fn_arg_info "i-path" "Installs the devos cli tool to /usr/local/bin."
runtime_fn_arg_parse "$@"

# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
# # shellcheck source=/root/.bashrc
# source /root/.bashrc
# nvm install $runtime_node_version
# nvm use $runtime_node_version
# source /root/.bashrc
# npm install --global pnpm @vscode/vsce
# source /root/.bashrc

#
# Maybe clean this up, but the idea is to automatically install
# the cli we use to bootstrap the system on our laptop.
#
SOFTWARE_NAME="devos"
SOURCE_BIN_PATH="/root/.$SOFTWARE_NAME/bin/$SOFTWARE_NAME"
BIN_PATH="/usr/local/bin/$SOFTWARE_NAME"
if [ -f "$BIN_PATH" ]; then
  rm -f "$BIN_PATH"
fi
{
  echo "#!/usr/bin/env bash"
  echo ""
  echo "# This script was generated by the devos installer at $(date)."
  echo ""
  echo "source \"$SOURCE_BIN_PATH\""
} >>"$BIN_PATH"
chmod +x "$SOURCE_BIN_PATH"
chmod +x "$BIN_PATH"
