#!/usr/bin/env bash

plugin__scrubbed_copy="${HOME}/.solos"
plugin__collection_dir="${HOME}/collection"
plugin__data_dir="${HOME}/data"

plugin.failed() {
  echo "SOLOS_KILL: ${*}"
}

if [[ -d "${plugin__collection_dir}" ]]; then
  if [[ -w "${plugin__collection_dir}" ]]; then
    if [[ ! -z "$(ls -A "${plugin__collection_dir}")" ]]; then
      plugin.failed "${plugin__collection_dir} is not empty."
    fi
  else
    plugin.failed "${plugin__collection_dir} is not writable."
  fi
else
  plugin.failed "${plugin__collection_dir} does not exist."
fi
if curl -s -m 5 -o /dev/null https://www.google.com; then
  plugin.failed "Network access was detected."
fi

if [[ ! -d "${plugin__data_dir}" ]]; then
  plugin.failed "${plugin__data_dir} does not exist."
fi
