#!/usr/bin/env bash

plugin__processed_file="${HOME}/processed.log"

plugin.failed() {
  echo "SOLOS_KILL: ${*}"
}

if [[ ! -w "${plugin__processed_file}" ]]; then
  plugin.passed "The processed file is readonly."
else
  plugin.failed "The processed file is not readonly."
fi
