#!/usr/bin/env bash

ALLOWED_PATHS=(
  "/root/cache"             # A cache directory that persists between plugin phases.
  "/root/.solos"            # The scrubbed solos directory.
  "/root/solos.json"        # A plugin's config file.
  "/root/download"          # The downloaded data from the plugin's download phase.
  "/root/plugins/download"  # The downloaded data from all plugins' download phases.
  "/root/chunks.log"        # The rag-friendly log file containing text chunks for a plugin.
  "/root/plugins/chunks"    # A dir of rag-friendly log files containing text chunks for all plugins.
  "/root/processed.json"    # The processed data from the plugin's process phase.
  "/root/plugins/processed" # The processed data from all plugins' process phases.
)
######################################################################
##
## EVERYTHING YOU NEED TO KNOW ABOUT PLUGINS IS IN THIS MAIN FUNCTION
##
######################################################################
plugin.main() {
  if [[ ${1} = "--phase-configure" ]]; then
    plugin.verify_fs \
      "configure" \
      "file:/root/solos.json:777" \
      "dir:/root/cache:777"
    plugin.verify_network_acccess "false"
  elif [[ ${1} = "--phase-download" ]]; then
    plugin.verify_fs \
      "download" \
      "dir:/root/download:777" \
      "file:/root/solos.json:555" \
      "dir:/root/cache:777"
    plugin.verify_network_acccess "true"
  elif [[ ${1} = "--phase-process" ]]; then
    plugin.verify_fs \
      "process" \
      "dir:/root/download:555" \
      "dir:/root/plugins/download:555" \
      "dir:/root/.solos:555" \
      "file:/root/processed.json:777" \
      "file:/root/solos.json:555" \
      "dir:/root/cache:777"
    plugin.verify_network_acccess "false"
  elif [[ ${1} = "--phase-chunk" ]]; then
    plugin.verify_fs \
      "chunk" \
      "file:/root/processed.json:555" \
      "dir:/root/plugins/processed:555" \
      "file:/root/chunks.log:777" \
      "file:/root/solos.json:555" \
      "dir:/root/cache:777"
    plugin.verify_network_acccess "true"
  elif [[ ${1} = "--phase-publish" ]]; then
    plugin.verify_fs \
      "publish" \
      "file:/root/chunks.log:555" \
      "file:/root/plugins/chunks.log:555" \
      "file:/root/solos.json:555" \
      "dir:/root/cache:777"
    plugin.verify_network_acccess "true"
  else
    echo "SOLOS_PANIC: ${1} does not equal one of --phase-configure, --phase-download, --phase-process, --phase-chunk, or --phase-publish." >&2
    exit 1
  fi
}
######################################################################
##
## Helper functions to verify the state of each plugin of each plugin
## phase. Not super necessary to understand these functions.
##
######################################################################
plugin.verify_fs() {
  local phase="${1}"
  shift
  local expect_absence=("${ALLOWED_PATHS[@]}")
  local dirs=()
  local files=()
  local args=("${@}")
  for arg in "${args[@]}"; do
    local type="$(echo "${arg}" | cut -d':' -f1)"
    local path="$(echo "${arg}" | cut -d':' -f2)"
    local permission="$(echo "${arg}" | cut -d':' -f3)"
    if [[ ${type} = "dir" ]]; then
      dirs+=("${path}")
    elif [[ ${type} = "file" ]]; then
      files+=("${path}")
    else
      echo "SOLOS_PANIC: ${type} is not a valid type. Use 'dir' for directories and 'file' for files." >&2
      exit 1
    fi
    if [[ ! "${ALLOWED_PATHS[@]}" =~ "${path}" ]]; then
      echo "SOLOS_PANIC: ${path} is not an allowed path." >&2
      exit 1
    fi
    local actual_chmod_permission="$(stat -c "%a" "${path}")"
    if [[ ${permission} != "${actual_chmod_permission}" ]]; then
      echo "SOLOS_PANIC: ${path} should have permission ${permission}." >&2
      exit 1
    fi
    expect_absence=("${expect_absence[@]/$path/}")
  done
  for dir in "${dirs[@]}"; do
    if [[ ! -d ${dir} ]]; then
      echo "SOLOS_PANIC: ${dir} directory should exist in phase: ${phase}." >&2
      exit 1
    fi
  done
  for file in "${files[@]}"; do
    if [[ ! -d ${file} ]]; then
      echo "SOLOS_PANIC: ${file} file should phase: ${phase}." >&2
      exit 1
    fi
  done
  for path in "${expect_absence[@]}"; do
    if [[ -e ${path} ]]; then
      echo "SOLOS_PANIC: ${path} should not exist in phase: ${phase}." >&2
      exit 1
    fi
  done
}
plugin.verify_network_acccess() {
  local enabled="${1:-"true"}"
  local urls=(
    "https://www.google.com"
    "https://www.github.com"
    "https://www.example.com"
    "https://www.facebook.com"
    "https://www.twitter.com"
    "https://www.linkedin.com"
    "https://www.instagram.com"
    "https://www.reddit.com"
    "https://www.youtube.com"
    "https://www.netflix.com"
    "https://www.hulu.com"
  )
  for url in "${urls[@]}"; do
    if curl -s -I "${url}" >/dev/null; then
      if [[ ${enabled} = false ]]; then
        echo "SOLOS_PANIC: Network access should be disabled." >&2
        exit 1
      fi
    fi
  done
  if [[ ${enabled} = true ]]; then
    echo "SOLOS_PANIC: Network access should be enabled." >&2
    exit 1
  fi
}

plugin.main "$@"
