#!/usr/bin/env bash

plugin__data_dir="${HOME}/data"
plugin__cache_dir="${HOME}/cache"

plugin.failed() {
  echo "SOLOS_KILL: ${*}"
}

# Data
if [[ -d "${plugin__data_dir}" ]]; then
  if [[ -w "${plugin__data_dir}" ]]; then
    if [[ ! -z "$(ls -A "${plugin__data_dir}")" ]]; then
      plugin.failed "${plugin__data_dir} is not empty."
    fi
  else
    plugin.failed "${plugin__data_dir} is not writable."
  fi
else
  plugin.failed "${plugin__data_dir} does not exist."
fi

# Cache
if [[ -d "${plugin__cache_dir}" ]]; then
  if [[ -w "${plugin__cache_dir}" ]]; then
    if [[ ! -z "$(ls -A "${plugin__cache_dir}")" ]]; then
      plugin.failed "${plugin__cache_dir} is not empty."
    fi
  else
    plugin.failed "${plugin__cache_dir} is not writable."
  fi
else
  plugin.failed "${plugin__cache_dir} does not exist."
fi

# Network access
if ! curl -s -m 5 -o /dev/null https://www.google.com; then
  plugin.failed "Network access is blocked."
fi
