#!/usr/bin/env bash

# WARNING: the lack of initial "cd" is intentional.
# This script is strictly meant to be sourced from the scp'd bootstrap script.
# Refer to installer/boot/bootstrap.sh for the working directory.

# shellcheck source=shared.packages.sh
. debian12/.boot/shared.packages.sh
# shellcheck source=../../debian12/install.node.sh
. debian12/install.node.sh
# shellcheck source=../../debian12/hook.alias.sh
. debian12/hook.alias.sh
# shellcheck source=../../debian12/install.clone-repos.sh
. debian12/install.clone-repos.sh
# shellcheck source=../../debian12/install.apps.sh
. debian12/install.apps.sh
# shellcheck source=../../debian12/hook.docs.sh
. debian12/hook.docs.sh
#
# Maybe clean this up, but the idea is to automatically install
# the cli we use to bootstrap the system on our laptop.
#
SOURCE_BIN_PATH="/root/solos/bin/solos"
BIN_PATH="/usr/local/bin/solos"
if [ -f "$BIN_PATH" ]; then
  rm -f "$BIN_PATH"
fi
{
  echo "#!/usr/bin/env bash"
  echo ""
  echo "# This script was generated by the solos installer at $(date)."
  echo ""
  echo "$SOURCE_BIN_PATH \"\$@\""
} >>"$BIN_PATH"
chmod +x "$SOURCE_BIN_PATH"
chmod +x "$BIN_PATH"
