#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

# shellcheck source=../../.env.sh
. ../../.env.sh
# shellcheck source=./.runtime/runtime.sh
. ./.runtime/runtime.sh

fn_arg_info "i-path" "Installs the solos cli tool to /usr/local/bin."
fn_arg_parse "$@"

# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
# # shellcheck source=/root/.bashrc
# . /root/.bashrc
# nvm install $runtime_node_version
# nvm use $runtime_node_version
# . /root/.bashrc
# npm install --global pnpm @vscode/vsce
# . /root/.bashrc

#
# Maybe clean this up, but the idea is to automatically install
# the cli we use to bootstrap the system on our laptop.
#
SOFTWARE_NAME="solos"
SOURCE_BIN_PATH="/root/.$SOFTWARE_NAME/bin/$SOFTWARE_NAME"
BIN_PATH="/usr/local/bin/$SOFTWARE_NAME"
if [ -f "$BIN_PATH" ]; then
  rm -f "$BIN_PATH"
fi
{
  echo "#!/usr/bin/env bash"
  echo ""
  echo "# This script was generated by the solos installer at $(date)."
  echo ""
  echo ". \"$SOURCE_BIN_PATH\""
} >>"$BIN_PATH"
chmod +x "$SOURCE_BIN_PATH"
chmod +x "$BIN_PATH"
